return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "c",
        "css",
        "csv",
        "dockerfile",
        "fish",
        "gitignore",
        "html",
        "javascript",
        "jsdoc",
        "json",
        "kdl",
        "lua",
        "luadoc",
        "markdown",
        "markdown_inline",
        "php",
        "printf",
        "query",
        "regex",
        "robots",
        "scss",
        "ssh_config",
        "tmux",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "yaml",
      },
      -- Autoinstall languages that are not installed
      auto_install = true,
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = { "ruby" },
      },
      indent = { enable = true, disable = { "ruby" } },
    },
  },
}
