# Alias List
alias actm 'act --container-architecture linux/amd64 -r --secret-file act.secrets'
alias ls 'eza --long --icons --header --no-user --sort=type'
alias la 'eza --long --icons --header --no-user --sort=type --all'
alias las 'localias'
alias ld 'lazydocker'
alias lg 'lazygit'
alias mux 'tmuxinator'
alias muxs 'tmuxinator start $(tmuxinator list --newline | fzf)'
alias rm 'trash'
alias zj 'zellij'
