# Abbreviation List
abbr -a -- abbra 'abbr --add'
abbr -a -- addfishpath 'set --universal --append fish_user_paths'
abbr -a -- brewcleanup 'brew cleanup --prune=0'
abbr -a -- brewup 'brew update && brew upgrade && brew cleanup'
abbr -a -- brewupx 'brew update && brew outdated --cask --greedy --verbose && brew upgrade --greedy --verbose && brew cleanup'
abbr -a -- c clear
abbr -a -- cc 'clear; tmux clear-history; clear'
abbr -a -- co 'code .'
abbr -a -- cpwd 'pwd | pbcopy'
abbr -a -- ct 'cloudflared tunnel'
abbr -a -- dc 'docker compose'
abbr -a -- dcr 'docker compose restart'
abbr -a -- dcs 'docker compose start'
abbr -a -- dcsp 'docker compose stop'
abbr -a -- dcu 'docker compose up'
abbr -a -- dcud 'docker compose up -d'
abbr -a -- dipa 'docker image prune --all'
abbr -a -- dlf 'docker logs --follow'
abbr -a -- dnsflush 'sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder'
abbr -a -- dockerclean 'docker system prune -a'
abbr -a -- dotc chezmoi
abbr -a -- dotca 'chezmoi -v apply'
abbr -a -- dotcc 'code ~/.local/share/chezmoi'
abbr -a -- dotccd 'chezmoi cd'
abbr -a -- dotcu 'chezmoi -v update'
abbr -a -- dps 'docker ps'
abbr -a -- dpsa 'docker ps -a'
abbr -a -- f 'fuck'
abbr -a -- ff 'fd -t f | fzf'
abbr -a -- fishconfig 'nvim ~/.config/fish/config.fish'
abbr -a -- gbd 'git branch -d'
abbr -a -- gbls 'git branch --all'
abbr -a -- gc 'git checkout'
abbr -a -- gitc 'git remote prune origin'
abbr -a -- gitclean 'git remote prune origin'
abbr -a -- gitcleanmerged git\ branch\ --merged\ main\ \|\ grep\ -v\ \"^\\\*\ main\"\ \|\ xargs\ -n\ 1\ -r\ git\ branch\ -d
abbr -a -- glo 'git log --oneline --graph --decorate --all'
abbr -a -- gph 'git push origin'
abbr -a -- gpo 'git pull origin'
abbr -a -- grh 'git reset --hard'
abbr -a -- gst 'git status'
abbr -a -- j jump
abbr -a -- lx 'exa -l -g --icons'
abbr -a -- lxa 'exa -l -g --icons -a'
abbr -a -- lxt 'exa -l -g --icons --tree --level=2'
abbr -a -- lxta 'exa -l -g --icons --tree --level=2 -a'
abbr -a -- lzd 'lazydocker'
abbr -a -- nb 'nr build'
abbr -a -- nd 'nr dev'
abbr -a -- ndp 'nr deploy'
abbr -a -- ncu 'npx npm-check-updates'
abbr -a -- npmls 'npm ls -g --depth=0'
abbr -a -- npmsize 'find . -name "node_modules" -type d -prune -print | xargs du -chs'
abbr -a -- npmup 'npx npm-check -gu'
abbr -a -- o 'open .'
abbr -a -- pwdc 'pwd | pbcopy'
abbr -a -- starshipconfig 'nvim ~/.config/starship.toml'
abbr -a -- tn 'tmux new-session -A -s default'
abbr -a -- tk 'tmux kill-server'
abbr -a -- upx 'smug upx -i -a'
abbr -a -- vf 'fzf | xargs -o nvim'
abbr -a -- wr wrangler
abbr -a -- yup 'yarn global upgrade-interactive --latest'